name: Demo App ArgoCD CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements.txt

    - name: Run Flask application for a short period
      run: |
        cd app
        nohup flask run &
        sleep 5
        pkill -f "flask"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd app
        python -m unittest discover -s .

  dockerize:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd app
        export sha_short=$(git rev-parse --short ${GITHUB_SHA})
        docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-app:$sha_short .
        docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:$sha_short

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Clone Helm Repository
        uses: actions/checkout@v4
        with:
          repository: 'BoraKostem/demo-app-Helm'
          path: ./helm
          token: ${{ secrets.PAT }}

      - name: Clone ArgoCD Repository    
        uses: actions/checkout@v4
        with:
          repository: 'BoraKostem/demo-app-ArgoCD'
          path: ./argocd
          token: ${{ secrets.PAT }}
          
      - name: Generate Kubernetes Manifests with Helm
        env:
          NAMESPACE: demo-app
          IMAGE_REPO: borakostem/
          IMAGE_NAME: demo-app
        run: |
          cd helm
          export sha_short=$(git rev-parse --short ${GITHUB_SHA})
          helm template release demo-app --set namespace=${NAMESPACE}, --set image.repository=${IMAGE_REPO}${IMAGE_NAME}, --set image.tag=$sha_short, --set fullnameOverride=${IMAGE_NAME} --output-dir ./

      - name: Update ArgoCD Manifests
        run: |
          cd argocd
          export sha_short=$(git rev-parse --short ${GITHUB_SHA})
          cd ..
          rm -rf argocd/manifests/apps/demo-app/*
          mv ./demo-app/templates/* argocd/manifests/apps/demo-app/
          git config --global user.email "fenari.kostem@gmail.com"
          git config --global user.name "CI_CD Bot"
          cd argocd
          git add .
          git commit -m "Update demo-app commit ${sha_short}"
          git remote set-url origin  https://github.com/BoraKostem/demo-app-ArgoCD.git
          git push origin main